cd repo && remove *
wget https://aur.archlinux.org/cgit/aur.git/snapshot/brave-nightly-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/microsoft-edge-dev-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/discord-canary.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/python-proton-client.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/fvs.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/icoextract.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/patool.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/vkbasalt-cli.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/mozilla-common.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/playonlinux.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/visual-studio-code-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/webstorm-eap.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/jetbrains-fleet.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/pycharm-edu.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/pycharm-professional.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/noisetorch.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/appimagelauncher.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/pulsar-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/waterfox-g4-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/ventoy-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/waterfox-g-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/pycharm-community-jre.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/slack-desktop.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/heroic-games-launcher-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/android-studio.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/anydesk-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/inxi.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/heroku-cli-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/microsoft-edge-stable-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/python2-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/yay-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-espresso.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-gsconnect.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-dash-to-dock.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-clipboard-indicator.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-nasa-apod.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-openweather.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-blur-my-shell.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-no-overview.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-dash-to-panel.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-media-controls.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-caffeine.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-gtk4-desktop-icons-ng.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-ddterm.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gnome-shell-extension-just-perfection-desktop.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/brave-beta-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/danser.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/python-protonvpn-nm-lib.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/protonvpn-gui.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/python-pynput.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/etcher-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/discord-rpc-cli.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/ungoogled-chromium-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/rustdesk-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/snapd.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/vmware-workstation.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/vmware-keymaps.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/vmware-unlocker-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/microsoft-edge-beta-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/armcord-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/octopi.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/jellyfin-media-player.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/gdlauncher-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/tlauncher-org.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/lunar-client.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/virtualbox-ext-oracle.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/vscodium-bin.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/jdownloader2.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/betterdiscord-installer.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/prismlauncher-bin.tar.gz
ls *.tar.gz |xargs -n1 tar -xzf
rm -rf *.tar.gz