cd .. && cd repo
git clone https://aur.archlinux.org/brave-nightly-bin.git
git clone https://aur.archlinux.org/microsoft-edge-dev-bin.git
git clone https://aur.archlinux.org/discord-canary.git
git clone https://aur.archlinux.org/python-proton-client.git
git clone https://aur.archlinux.org/fvs.git
git clone https://aur.archlinux.org/icoextract.git
git clone https://aur.archlinux.org/patool.git
git clone https://aur.archlinux.org/vkbasalt-cli.git
git clone https://aur.archlinux.org/mozilla-common.git
git clone https://aur.archlinux.org/playonlinux.git
git clone https://aur.archlinux.org/visual-studio-code-bin.git
git clone https://aur.archlinux.org/webstorm-eap.git
git clone https://aur.archlinux.org/jetbrains-fleet.git
git clone https://aur.archlinux.org/pycharm-edu.git
git clone https://aur.archlinux.org/pycharm-professional.git
git clone https://aur.archlinux.org/noisetorch.git
git clone https://aur.archlinux.org/appimagelauncher.git
git clone https://aur.archlinux.org/pulsar-bin.git
git clone https://aur.archlinux.org/waterfox-g4-bin.git
git clone https://aur.archlinux.org/ventoy-bin.git
git clone https://aur.archlinux.org/waterfox-g-bin.git
git clone https://aur.archlinux.org/pycharm-community-jre.git
git clone https://aur.archlinux.org/slack-desktop.git
git clone https://aur.archlinux.org/heroic-games-launcher-bin.git
git clone https://aur.archlinux.org/android-studio.git
git clone https://aur.archlinux.org/anydesk-bin.git
git clone https://aur.archlinux.org/inxi.git
git clone https://aur.archlinux.org/heroku-cli-bin.git
git clone https://aur.archlinux.org/microsoft-edge-stable-bin.git
git clone https://aur.archlinux.org/python2-bin.git
git clone https://aur.archlinux.org/yay-bin.git
git clone https://aur.archlinux.org/gnome-shell-extension-espresso.git
git clone https://aur.archlinux.org/gnome-shell-extension-gsconnect.git
git clone https://aur.archlinux.org/gnome-shell-extension-dash-to-dock.git
git clone https://aur.archlinux.org/gnome-shell-extension-clipboard-indicator.git
git clone https://aur.archlinux.org/gnome-shell-extension-nasa-apod.git
git clone https://aur.archlinux.org/gnome-shell-extension-openweather.git
git clone https://aur.archlinux.org/gnome-shell-extension-blur-my-shell.git
git clone https://aur.archlinux.org/gnome-shell-extension-no-overview.git
git clone https://aur.archlinux.org/gnome-shell-extension-dash-to-panel.git
git clone https://aur.archlinux.org/gnome-shell-extension-media-controls.git
git clone https://aur.archlinux.org/gnome-shell-extension-caffeine.git
git clone https://aur.archlinux.org/gnome-shell-extension-gtk4-desktop-icons-ng.git
git clone https://aur.archlinux.org/gnome-shell-extension-ddterm.git
git clone https://aur.archlinux.org/gnome-shell-extension-just-perfection-desktop.git
git clone https://aur.archlinux.org/brave-beta-bin.git
git clone https://aur.archlinux.org/danser.git
git clone https://aur.archlinux.org/python-protonvpn-nm-lib.git
git clone https://aur.archlinux.org/protonvpn-gui.git
git clone https://aur.archlinux.org/python-pynput.git
git clone https://aur.archlinux.org/etcher-bin.git
git clone https://aur.archlinux.org/discord-rpc-cli.git
git clone https://aur.archlinux.org/ungoogled-chromium-bin.git
git clone https://aur.archlinux.org/rustdesk-bin.git
git clone https://aur.archlinux.org/snapd.git
git clone https://aur.archlinux.org/vmware-workstation.git
git clone https://aur.archlinux.org/vmware-keymaps.git
git clone https://aur.archlinux.org/vmware-unlocker-bin.git
git clone https://aur.archlinux.org/microsoft-edge-beta-bin.git
git clone https://aur.archlinux.org/armcord-bin.git
git clone https://aur.archlinux.org/octopi.git
git clone https://aur.archlinux.org/jellyfin-media-player.git
git clone https://aur.archlinux.org/gdlauncher-bin.git
git clone https://aur.archlinux.org/tlauncher-org.git
git clone https://aur.archlinux.org/lunar-client.git
git clone https://aur.archlinux.org/virtualbox-ext-oracle.git
git clone https://aur.archlinux.org/vscodium-bin.git
git clone https://aur.archlinux.org/jdownloader2.git
git clone https://aur.archlinux.org/betterdiscord-installer.git
git clone https://aur.archlinux.org/prismlauncher-bin.git
git clone https://aur.archlinux.org/ttf-ms-fonts.git
git clone https://aur.archlinux.org/tela-circle-icon-theme.git
git clone https://aur.archlinux.org/qogir-gtk-theme-git.git
git clone https://aur.archlinux.org/mcmojave-cursors.git
git clone https://aur.archlinux.org/mkinitcpio-openswap.git
git clone https://aur.archlinux.org/alpm_octopi_utils.git
git clone https://aur.archlinux.org/github-desktop-bin.git
git clone https://aur.archlinux.org/vscodium-bin-marketplace.git
git clone https://aur.archlinux.org/distrobox.git
git clone https://aur.archlinux.org/termius.git
git clone https://aur.archlinux.org/brave-bin.git
git clone https://aur.archlinux.org/signal-desktop-beta.git
git clone https://aur.archlinux.org/payload-dumper-go.git
git clone https://github.com/phantomic12/ckbcomp.git
cd ckbcomp
rm -rf .git
cd ..
git clone https://github.com/phantomic12/calamares.git
cd calamares
rm -rf .git
cd ..