name: add new PKGBUILD (ghweb)
on:
  workflow_dispatch:
    inputs:
      new:
        description: aur pkgname
        required: true
        type: string

jobs:
  fetchsrc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Add package
        run: echo "git clone https://aur.archlinux.org/${{ inputs.new }}.git" >> misc-scripts/sources.sh

      - name: Commit Changed Files
        run: |     
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git checkout gnome
          git diff-index --quiet HEAD || git commit -am "add new package"
          git pull origin gnome --rebase=true # to avoid conflicts due to data races
          git push
