name: Automatically Build Images

on:
  push:
    branches: [gnome]
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  buildimage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        variant:         
          - gnome
          - cinnamon
    steps:
      - uses: actions/checkout@v3
      - run: tar -cvf dirs.tar airootfs/ efiboot/ syslinux/ profiledef.sh steps.sh pacman.conf packages.x86_64
      - name: Build ISO
        uses: phantomic12/mkarchiso-action@1.2
        with:
          command: cd iso/${{ matrix.variant }} && sh start.sh
      - name: Setup SSH
        uses: fastai/workflows/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: id_ecdsa
      - name: Prepare for Upload
        run: |
          THEDATE=`date +'%Y-%m-%d%---H-%M-%S'`
          mkdir -p images/${{ matrix.variant }}-iso/$THEDATE
          mv phantoms-arch-x86_64.iso images/${{ matrix.variant }}-iso/$THEDATE  
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh images/ "${{ secrets.USERNAME }}@frs.sourceforge.net:${{ matrix.variant }}-iso"
