name: Build Repo
on:
  push:
    branches: [gnome]

jobs:
  genmatrix:
    runs-on: ubuntu-latest

    outputs:
      build_matrix: ${{ steps.generate_build_matrix.outputs.build_matrix }}
    # check out the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Build matrix
        id: generate_build_matrix
        run: |
          # set variable
          cd repo
          pkgs=$(cat pkglist.txt)
          echo "Packages present: $pkgs"
          if [ -z "$pkgs" ]; then
          echo "::set-output name=is_empty::true"
          else
          echo "::set-output name=is_empty::false"
          fi
          # turn it into a json array
          build_matrix=$(echo "$pkgs" | jq -R . | jq -s . | jq -c .)
          # create build matrix with { pkgs: [ "pkg1", "pkg2" ] }
          echo "::set-output name=build_matrix::$build_matrix"
  build:
    needs: genmatrix
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.genmatrix.outputs.build_matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: phantomic/makepkgarch:latest
    steps:
      - name: Try and fix write permissions
        run: sudo chown -R build /home/build

      - name: Clone PKGBUILDs
        run: git clone https://aur.archlinux.org/${{ matrix.pkg }}.git

      - name: Build Package
        run: cd ${{ matrix.pkg }} && makepkg --syncdeps --noconfirm --install && mkdir phn-repo && mv *.zst phn-repo

      - name: Upload Built Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: phn-repo