name: Build Repo
on:
  push:
    branches: [gnome]

jobs:
  genmatrix:
    runs-on: ubuntu-latest

    outputs:
      build_matrix: ${{ steps.generate_build_matrix.outputs.build_matrix }}
    # check out the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Build matrix
        id: generate_build_matrix
        run: |
          # set variable
          cd repo
          pkgs=$(cat pkglist.txt)
          echo "Packages present: $pkgs"
          if [ -z "$pkgs" ]; then
          echo "::set-output name=is_empty::true"
          else
          echo "::set-output name=is_empty::false"
          fi
          # turn it into a json array
          build_matrix=$(echo "$pkgs" | jq -R . | jq -s . | jq -c .)
          # create build matrix with { pkgs: [ "pkg1", "pkg2" ] }
          echo "::set-output name=build_matrix::$build_matrix"
  build:
    needs: genmatrix
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.genmatrix.outputs.build_matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Install Deps
        run: sudo pacman -Sy archlinux-keyring git
        
      - name: Clone PKGBUILDs
        run: git clone https://aur.archlinux.org/${{ matrix.pkg }}.git
      
      - name: Build Arch Linux package
        uses: FFY00/build-arch-package@v1
        with:
          PKGBUILD: $HOME/${{ matrix.pkg }}
          OUTDIR: $HOME/phn-repo

      - name: Upload Built Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: phn-repo