name: Update Repo
on:
  push:
    paths-ignore:      
          - "iso/**"
          - ".github/**"
  workflow_dispatch:

jobs:
  genmatrix:
    runs-on: ubuntu-latest

    outputs:
      build_matrix: ${{ steps.generate_build_matrix.outputs.build_matrix }}
      is_empty: ${{ steps.generate_build_matrix.outputs.is_empty }}

    # check out the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git fetch
      #- run: git checkout HEAD^

      - name: Generate Build matrix
        id: generate_build_matrix
        # generate build matrix by checking out changes in repo/
        run: |
          # get the list of changed folders in the current commit
          changed_folders=$(git diff --name-only HEAD^ | grep -oP 'repo\/(.+)\/' | sort -u )
          echo "Changed folders: $changed_folders"
          # if changed_folders is empty then set is empty to true
          if [ -z "$changed_folders" ]; then
            echo "::set-output name=is_empty::true"
          else
            echo "::set-output name=is_empty::false"
          fi
          # turn it into a json array
          #build_matrix=$(echo "$changed_folders" | jq -R . | jq -s . | jq -c .)
          # if there's only one folder then check if it's
          build_matrix=$(find repo/ | grep -oP 'repo\/(.+)\/' | sort -u | jq -R -s -c 'split("\n")[:-1]')
          # create build matrix with { changed_folders: [ "folder1", "folder2" ] }
          echo "::set-output name=build_matrix::$build_matrix"
          #echo "::set-output name=build_matrix::$build_matrix"

  build:
    needs: genmatrix
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.genmatrix.outputs.build_matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Arch Linux package
        uses: soloturn/build-aur-action@master
        with:
          repo-name: ${{ matrix.pkg }}
      - name: Move files
        run: mv *.tar.zst $HOME/phn-repo
      - name: Upload Built Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: $HOME/phn-repo