name: clean old packages
on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:


      - name: Download Everything
        run: |
          urls=$(curl https://github.com/phantomic12/phantomsarch/releases/expanded_assets/repo -s|grep "/phantomic12/phantomsarch/releases/download/repo/"|awk -F '"|"' '{print$2}')

          for i in ${urls[*]}; do 
              pkg=$(echo $i|awk -F '/' '{print$7}')
              echo Downloading $pkg
              aria2c -x 16 -s 16 https://github.com/$i
          done
          ls -R

      - name: delete old packages
        run: |
          REPO_NAME=phn-repo
          DND="DO_NOT_DELETE"

          if [ ! -d $DND ]; then
            mkdir $DND
          fi

          mv $(
          	tar tf $REPO_NAME.db |
          		awk -F/ 'NF==2{print $1}' |
          		sort -u |
          		while read line; do
          			ls $line*
          		done
          ) -t $DND

          mv $REPO_NAME.db $REPO_NAME.db.tar.gz $REPO_NAME.files $REPO_NAME.files.tar.gz -t $DND
          ls | grep -v $DND | xargs rm -rfv
          mv $DND/* .
          rmdir $DND
          ls -R


      - name: Upload Packages
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          removeArtifacts: true
          tag: "repo"
          artifacts: "./*.zst"
          token: ${{ secrets.PAT }}
