name: clean old packages
  workflow_dispatch:

jobs:
  fetchsrc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Download Everything
        run: |
          pacman -Syu --needed aria2 openssh sshpass base-devel --noconfirm
          urls=$(curl https://github.com/phantomic12/phantomsarch/releases/expanded_assets/repo -s|grep "/phantomic12/phantomsarch/releases/download/repo/"|awk -F '"|"' '{print$2}')

          for i in ${urls[*]}; do 
              pkg=$(echo $i|awk -F '/' '{print$7}')
              echo Downloading $pkg
              aria2c -x 16 -s 16 https://github.com/$i
          done

      - name: Upload Packages
        run: sh misc-scripts/repodel.sh phn-repo



      - name: Upload Packages
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "repo"
          artifacts: "./*.zst"
          token: ${{ secrets.PAT }}
