name: Delete Repo Assets
on:
  schedule:
    - cron: "0 0 * * 5-6"
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
      steps:
      - name: Clean up packages
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.PAT }}
          tag: repo
          assets: '*.zst'
      
      - name: Clean up packages
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.PAT }}
          tag: repo
          assets: 'phn-repo.*'