name: Automatically Build Images

on:
  workflow_dispatch:

jobs:
  fetchsrc:
    runs-on: ubuntu-latest
    steps:
      - name: Download Everything
        run: |
          urls=$(curl https://github.com/phantomic12/phantomsarch/releases/expanded_assets/repo -s|grep "/phantomic12/phantomsarch/releases/download/repo/"|awk -F '"|"' '{print$2}')

          for i in ${urls[*]}; do 
              pkg=$(echo $i|awk -F '/' '{print$7}')
              echo Downloading $pkg
              aria2c -x 16 -s 16 https://github.com/$i
          done

      - name: Setup SSH
        uses: fastai/workflows/ssh@master
        with:
            ssh_key: ${{ secrets.SSH_KEY }}
            key_file: id_ecdsa

      - name: Mirror to SF
        run: |
          mkdir repo && mv * repo
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh repo "${{ secrets.USERNAME }}@frs.sourceforge.net:$/home/pfs/project/phn-repo/new"          
