name: Trigger Mass Rebuild
on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 2
      - run: git fetch

      - name: Fetch P
        run: cd repo && rm -rf * && touch dummy

      - name: Commit Changed Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync PKGBUILDS
          commit_user_name: phantomic12_automated
  fetchsrc:
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch PKGBUILDS
        run: sh misc-scripts/clone.sh

      - name: Commit Changed Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync PKGBUILDS
          commit_user_name: phantomic12_automated