name: test dir

on:
  push:
    branches: [gnome]
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  buildimage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        variant:         
          - gnome
          - cinnamon
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - run: pacman -Sy
      - run: cd iso/${{ matrix.variant }} && mkdir out && cd out && touch phantomsarch-2023.02-x86_64.iso
      - name: Setup SSH
        uses: fastai/workflows/ssh@master
        with:
            ssh_key: ${{ secrets.SSH_KEY }}
            key_file: id_ecdsa
      - run: |
          THEDATE=`date +'%Y-%m-%d%---H-%M-%S'`
          mkdir -p images/${{ matrix.variant }}-iso/$THEDATE
          mv iso/${{ matrix.variant }}/out/phantoms-arch-*-x86_64.iso images/${{ matrix.variant }}-iso/$THEDATE  
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh images/ "${{ secrets.USERNAME }}@frs.sourceforge.net:${{ matrix.variant }}-iso"
