name: Test Upload Function

on:
  push:
    branches: [cinn-cldvm]

jobs:
  upload-to-sourceforge:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: fastai/workflows/ssh@master
      with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: id_ecdsa
    - name: Download Artifacts
      run: |
        sudo apt update
        sudo apt-get -y install wget 
        wget -O phantoms-arch-x86_64.iso https://freetestdata.com/wp-content/uploads/2022/02/Free_Test_Data_5MB_AVI.avi
    - name: Prepare for Upload
      run: |
        THEDATE=`date +%Y%m%d_%H:%M:%S`
        mkdir -p images/cinn-cldvm/$THEDATE
        mv phantoms-arch-x86_64.iso images/cinn-cldvm/$THEDATE
        ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
        sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh images/ "${{ secrets.USERNAME }}@frs.sourceforge.net:${{ secrets.SOURCEFORGE_DIR }}"
