name: Update PKGBUILDS
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  fetchsrc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch PKGBUILDS
        run: sh misc-scripts/clone.sh

      - name: Commit Changed Files
        run: |       
          git add -A
          git checkout gnome
          git diff-index --quiet HEAD || git commit -am "update pkgbuilds"
          git pull origin gnome --rebase=true # to avoid conflicts due to data races
          git push