name: Update PKGBUILDS
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  fetchsrc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch PKGBUILDS
        run: sh misc-scripts/clone.sh

      - name: Commit Changed Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync PKGBUILDS
          commit_user_name: phantomic12_automated